### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by fernandex00** [sytone/hassio-addons#1]
With hassOS the addon can not install i get this error
`ERROR (SyncWorker_13) [hassio.docker.addon] Can't build 64f57845/aarch64-addon-magic_mirror:0.23.3: The command '/bin/sh -c git clone --depth 1 -b master https://github.com/MichMich/MagicMirror.git . && npm install --unsafe-perm' returned a non-zero code: 1 `

**Comment by sytone** [comment]
May have been a change in the base image. will have to do a update and look.


Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Comment by fernandex00** [comment]
thanks @sytone hope you can update the addon, to be able to install it ,is very good

**Comment by sytone** [comment]
I went though and updated HA, uninstalled and reinstalled and it all worked fine. Do you have any other error logs?

**Comment by fernandex00** [comment]
i return to hassio with resin os and works , the problem was when  i was on hassOS

**Comment by erlendsellie** [comment]
Any update on this?

**Comment by erlendsellie** [comment]
Hassio on HassOS works as long as it's 32bit.
Startup is extremely slow though, as it runs "cloning MODULE" at each startup. No modules found under /modules.

**Comment by gkreitz** [comment]
Happened to me too, on a 64-bit hass.io. Same error message in the logs. Seems to be the issue MichMich/MagicMirror#1462. Apparently MagicMirror depends on a version of electron without arm64 builds. There is an ugly workaround (force arch to `armv7l` during npm install) mentioned in the linked issue, but hopefully upstream will fix this soon.

Attaching to the container while it was building, I grabbed this npm output:
```~ # docker attach --no-stdin 6613ebd80098
npm WARN deprecated nomnom@1.8.1: Package no longer supported. Contact support@npmjs.com for more info.

> uws@0.14.5 install /opt/magic_mirror/node_modules/uws
> node-gyp rebuild > build_log.txt 2>&1 || exit 0

> electron-chromedriver@1.7.1 install /opt/magic_mirror/node_modules/spectron/node_modules/electron-chromedriver
> node ./download-chromedriver.js

/opt/magic_mirror/node_modules/spectron/node_modules/electron-chromedriver/download-chromedriver.js:16
  if (error != null) throw error
                     ^

Error: Failed to find Electron v1.7.0 for linux-arm64 at https://github.com/electron/electron/releases/download/v1.7.0/chromedriver-v1.7.0-linux-arm64.zip
    at Request.<anonymous> (/opt/magic_mirror/node_modules/nugget/index.js:169:61)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at Request.onRequestResponse (/opt/magic_mirror/node_modules/request/request.js:1068:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:543:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:112:17)
    at TLSSocket.socketOnData (_http_client.js:440:20)
    at emitOne (events.js:116:13)
npm WARN grunt-stylelint@0.10.1 requires a peer of stylelint@^9.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN acorn-jsx@5.0.1 requires a peer of acorn@^6.0.0 but none is installed. You must install peer dependencies yourself.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron-chromedriver@1.7.1 install: `node ./download-chromedriver.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the electron-chromedriver@1.7.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-11-23T22_57_02_688Z-debug.log
```

**Comment by vipk31** [comment]
but can not install
log:
19-08-12 13:38:18 INFO (MainThread) [hassio.store.git] Clone add-on https://github.com/sytone/hassio-addons repository
19-08-12 13:38:23 WARNING (MainThread) [hassio.store.data] Can’t read /data/addons/git/64f57845/magic_mirror/config.json: required key not provided @ data[‘arch’]. Got None
19-08-12 13:38:23 INFO (MainThread) [hassio.store] Load add-ons from store: 59 all - 0 new - 0 remove

please help me
system : ubuntu 18.04
 Home Assistant 0.97.2

**Comment by bouwew** [comment]
I've made a copy of this repository and hopefully fixed the above error. Please go here: https://github.com/bouwew/hassio-addons-1
and try it.

**Comment by roessi** [comment]
Hello
I tried to install it on my N2+ but I gor this error message:


The command '/bin/ash -o pipefail -c apk add --no-cache git nodejs nodejs-npm curl wget unzip && npm set unsafe-perm true && npm i npm@latest -g' returned a non-zero code: 1

Can you help

**Comment by bouwew** [comment]
@roessi do you get this with  my version (see my previous post above)?

**Comment by roessi** [comment]
> @roessi do you get this with my version (see my previous post above)?

Hi, yes I added your repository to my Add-on Store.

Hass.IO Magic Mirror add-on repository
Sytone <github@sytone.com>
https://github.com/sytone/hassio-addons


Your Link above does not work.
 https://github.com/bouwew/hassio-addons-1 took me to https://github.com/bouwew/sytone-hassio-addons

**Comment by bouwew** [comment]
Correct, I've changed the name of the repository, but the new link should work, others are using it successfully.
I've also changed the info in the repository showing myself as the active maintainer. Please remove and re-add my repository https://github.com/bouwew/sytone-hassio-addons and try again.

**Comment by roessi** [comment]
Hi,
so I tried this:
1. remove the old MM Repository
2. restart the Host
3. add the repository https://github.com/bouwew/sytone-hassio-addons

Hass.IO Magic Mirror add-on repository - originally by Sytone
@bouwew
https://github.com/bouwew/sytone-hassio-addons

4. restart the Host
5. push the install button

And got the same error message

The command '/bin/ash -o pipefail -c apk add --no-cache git nodejs nodejs-npm curl wget unzip && npm set unsafe-perm true && npm i npm@latest -g' returned a non-zero code: 1

I'm using:
core-2021.9.6
supervisor-2021.09.0
Home Assistant OS 6.3

**Comment by bouwew** [comment]
Can you please check if there is more detailed error-info Configuration --> Logs --> LOAD FULL HOME ASSISTANT LOG?

**Comment by roessi** [comment]
Supervisor LOG:

21-09-14 11:24:50 INFO (SyncWorker_1) [supervisor.docker.addon] Starting build for 394ad856/aarch64-addon-magic_mirror:0.23.3
21-09-14 11:24:54 ERROR (SyncWorker_1) [supervisor.docker.addon] Can't build 394ad856/aarch64-addon-magic_mirror:0.23.3: The command '/bin/ash -o pipefail -c apk add --no-cache git nodejs nodejs-npm curl wget unzip     && npm set unsafe-perm true     && npm i npm@latest -g' returned a non-zero code: 1
21-09-14 11:24:54 ERROR (SyncWorker_1) [supervisor.docker.addon] Build log: 
Step 1/16 : ARG BUILD_FROM
Step 2/16 : FROM $BUILD_FROM
 ---> fc4c367ab17d
Step 3/16 : ENV LANG C.UTF-8
 ---> Using cache
 ---> c0ba78da5729
Step 4/16 : RUN apk add --no-cache git nodejs nodejs-npm curl wget unzip     && npm set unsafe-perm true     && npm i npm@latest -g
 ---> Running in 319610b00229
fetch https://dl-cdn.alpinelinux.org/alpine/v3.14/main/aarch64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.14/community/aarch64/APKINDEX.tar.gz
ERROR: unable to select packages:

  nodejs-npm (no such package):
    required by: world[nodejs-npm]
Removing intermediate container 319610b00229

**Comment by bouwew** [comment]
I'm getting the same error when I try to the installation.
I'm not an expert on this, maybe you can post your question in this topic: https://community.home-assistant.io/t/magic-mirror-addon-for-home-assistant/59650
